### ISSUE TITLE
my issue is that I cannot get any of these files to work :/

### ISSUE THREAD

**Issue by artlessknave** [batstyx/evemon-alpha-skill-plans#13]

**Comment by batstyx** [comment]
Can you be more specific?

1. Which file?
2. In what way can it not be used (i.e. is there an error message and what is that message)?
3. What source/version of EVEMon are you using if this is relevant to **2**?
 a. [evemondevteam/v3.0.3-4](https://github.com/evemondevteam/evemon/releases/tag/3.0.3)
 b. [peterhaneve/v4.0.20](https://github.com/peterhaneve/evemon/releases/tag/4.0.20)
 c. Other source/version
 
I'm assuming the xml plans still work with evemondevteam/v3.0.3-4 as that's what they were developed against and a quick test with the 'Blank Character Creator' in peterhaneve/v4.0.20 imported both 'Alpha Skills - All' and 'Alpha Skills - Drones' without error.

**Comment by artlessknave** [comment]
ah hell. nevermind, I figured out why it never works for me. once I knew that the files actually work for someone else, I opened it up and realized that "save link as" was adding html junk to it, instead of saving a text file like I apparently expected.
now that I got past that pebkac error, I notice that evemon flags 3 skills as omega required on an existing character, but not on the blank character. weird.
drone interfacing IV
medium drone operation V
heavy drone operation IV

**Comment by batstyx** [comment]
Ah, I did actually add the drone changes ages ago https://github.com/batstyx/evemon-alpha-skill-plans/tree/201907, just never applied them to the main branch. Oops.
In case you hadn't found it already, if you click the 'Raw' button at the top of a particular file's content (i.e. https://github.com/batstyx/evemon-alpha-skill-plans/blob/201907/by%20Group/Alpha%20Skills%20-%20Drones.xml) the 'Save As' on the raw content will then be xml instead of html.

Also, all the files are contained as xml in the zip attached to the release https://github.com/batstyx/evemon-alpha-skill-plans/releases. I'll try and remember how this all works and create a new release for the drone stuff.

**Comment by artlessknave** [comment]
I actually have a script pulling another script off github using the raw link....I just don't use github that often overall, never remember that save link as on the main list doesn't save as text, and totally forgot about the raw link. :|
it's good that did find a forgotten update though.
